### ISSUE TITLE
Ideogram: Restyle sidebar

### ISSUE THREAD

**Issue by jackparmer** [plotly/dash-bio#162]
Like all of Matthew's apps, the functionality is very cool and impressive, but the app design could be easier on the eyes. https://dash-bio.plotly.host/dash-ideogram/

![image](https://user-images.githubusercontent.com/1865834/52441522-d5428400-2aee-11e9-86a8-9a7a16aafee2.png)

**Comment by angeladaodao** [comment]
On it. Do we also need to wrap it with DDK?

**Comment by angeladaodao** [comment]
lmk if this is what you want. Do you want me to refresh all dash apps?

<img width="1277" alt="2019-02-07 8 51 47" src="https://user-images.githubusercontent.com/37411533/52454561-3469be00-2b1a-11e9-961b-ec59242466ce.png">

**Comment by jackparmer** [comment]
Wow, amazing - this looks sooo much better.

> On it. Do we also need to wrap it with DDK?

Yes

> Do you want me to refresh all dash apps?

Yes! All the Dash Bio apps could use some design attention. They all look like they were made by mad scientists right now :)

**Comment by shammamah** [comment]
@jackparmer - I didn't want to make the apps wrapped with DDK, since the source code is available online and I don't want to mislead people into thinking that it's possible to have that sort of layout with just the open-source libraries. Ideally, people should be able to visit the app code on GitHub, download it, and run it themselves.

**Comment by jackparmer** [comment]
> I didn't want to make the apps wrapped with DDK

OK, sounds good!

**Comment by shammamah** [comment]
Moved to #212.
