### ISSUE TITLE
NeedlePlot has unclear wording in tooltips

### ISSUE THREAD

**Issue by shammamah** [plotly/dash-bio#277]
* This is very unclear... Are both "name" and "coord" strings?
* I don't understand if "23-34" is a value example for "name" or "coord" (or both?).

_Originally posted by @mkcor in https://github.com/plotly/dash-bio/pull/267_

**Comment by Bachibouzouk** [comment]
the value for "name" field can be any string one pleases (so it could technically be "23-24)", the value for "coord" field should be a string formatted like `'%i-%i'%(coordinate_start, coordinate_stop)` and one should have `coordinate_start < coordinate_stop`

**Comment by mkcor** [comment]
I cannot find this text by exploring the app (https://dash-bio.herokuapp.com/dash-bio/needle-plot) and I cannot infer the meaning of this messy sentence with any certainty. Can you please proofread the sentence below and let me know if that was the intended meaning?
`"domains" is an array of JSON objects with required fields "name" and "coord" (both strings). "name" (example value: "start-stop") and "coord" (example value:  "23-34") give the start and end of the domains in protein coordinate.`

**Comment by Bachibouzouk** [comment]
@mkcor : the field `"name"` only need to be a string, there is no other format requirement, it is the name of the domain, i.e. its value will only be displayed as is (so it can well be "23-24", or "banana" or even ""). The field "`coord`" needs to be formatted like "23-24" because upon loading of the component a `split('-')` is used to extract the start and stop values of the domain, so "23-stop" will not work here.

**Comment by mkcor** [comment]
@Bachibouzouk Thank you! I'm therefore suggesting the updated wording as submitted in #293.
Meanwhile, I'd like to test what it's like in terms of end-user experience, but I can't find it in the (Needle Plot) demo app. Where do I have to navigate in order to be prompted for those instructions / descriptions? Thanks!

**Comment by Bachibouzouk** [comment]
@mkcor : normally you have to hover over a given `Div`
