### ISSUE TITLE
APP QA 2: Clustergram

### ISSUE THREAD

**Issue by jackparmer** [plotly/dash-bio#288]
- [ ] Colorbar needs a label (is it cm?)
- [x] "Petal length(cm)" (missing a space)
- [x] Dropdowns here are smushed
![image](https://user-images.githubusercontent.com/1865834/55284545-2a5c8280-5347-11e9-8b00-1218ee6092bd.png)
Need to change this:
![image](https://user-images.githubusercontent.com/1865834/55284561-88896580-5347-11e9-8b01-3ca6e6e8fb3c.png)
Looks much better:
![image](https://user-images.githubusercontent.com/1865834/55284566-90e1a080-5347-11e9-977c-f79ac965c941.png)

- [ ] Would be cool if had control to adjust levels of hierarchy in tree
- [x] Can't figure out add/remove group markers UI. What does group markers mean? 
- [ ] Can we coordinate zoom/drag on subplots?
![image](https://user-images.githubusercontent.com/1865834/55284594-f2a20a80-5347-11e9-9809-86a4036c68d9.png)
- [ ] Not sure if this is possible with plotly.js but would be cool if heatmaps had a max zoom-out, so you couldn't do things like this:
![image](https://user-images.githubusercontent.com/1865834/55284605-15342380-5348-11e9-8b0e-4a9996a940a5.png)
- [x] There's vertical gap here:
![image](https://user-images.githubusercontent.com/1865834/55284613-2e3cd480-5348-11e9-8489-f80ed4a46a43.png)
- [ ] Put a hyperlink here:
![image](https://user-images.githubusercontent.com/1865834/55284630-9d1a2d80-5348-11e9-939e-5d8d9faaf2ba.png)
- [x] This dropdown is messed:
![image](https://user-images.githubusercontent.com/1865834/55284636-b622de80-5348-11e9-8a66-854784a2304e.png)
- [x] x button shows up on top of text - make dropdown much longer:
![image](https://user-images.githubusercontent.com/1865834/55284641-c76beb00-5348-11e9-9a2f-c97bd12fa5c7.png)
- [ ] Plot needs a title
- [x] Default datasets should be oncology or genetics focused... Might be able to find data from an open journal article
- [x] Dropdown is touching horizontal rule here:
![image](https://user-images.githubusercontent.com/1865834/55284671-524ce580-5349-11e9-8185-ca44d259360b.png)

**Comment by shammamah** [comment]
That dropdown issue was happening because I had accidentally used less specific selectors when designing the sequence viewer app. All fixed now :) 

>Would be cool if had control to adjust levels of hierarchy in tree

What exactly do you mean by this? 

> Can we coordinate zoom/drag on subplots?

Argh, this was super difficult to get working in the first place and it sometimes still gives me issues. Hopefully the updates to `plotly.js` since I created the component will be helpful

> There's vertical gap here:

Yep, that's for the group markers. I made it look like [the MATLAB one](https://www.mathworks.com/help/bioinfo/ref/clustergram.html): 
![PerformHierarchicalClusteringOnGeneExpressionDataExample_05](https://user-images.githubusercontent.com/15622051/55406197-a1517100-5529-11e9-9bbc-b412ca4fb63e.png)
![2019-04-02 09 30 22 dash-bio plotly host 99425b3aba4c](https://user-images.githubusercontent.com/15622051/55406375-f7beaf80-5529-11e9-99a4-f55c152fa33a.png)

I agree that the instructions for adding row/group labels isn't super clear, so I'll make those a bit more obvious.
