### ISSUE TITLE
Dash Bio demo apps sample data downloads are broken when apps are run through `index.py`. 

### ISSUE THREAD

**Issue by shammamah** [plotly/dash-bio#442]

**Comment by IvoLeist** [comment]
Hello shammamah,

I stumbled over this bug as well while playing around with the molecule3d app (started via index.py). 

Below you find my workaround inspired by this recipe:
https://github.com/plotly/dash-recipes/blob/master/dash-download-file-link-server.py

In order to serve the file and not only download the html 
I added in dashbio_demos/app_molecule3d.py
```
from flask import send_from_directory
def routes(_app):
    @_app.server.route('/dash-bio/assets/sample_data/<path>')
    def serve_static(path):
        return send_from_directory(os.path.join('assets/sample_data/'), path)
```

And below in index.py
```
for key in apps:
    print(key)
    apps[key].callbacks(app)
    
    #added to enable def routes in app_molecule3d.py
    if key=="molecule3d":
        apps[key].routes(app) 
```

I hesitated to do a PR since this solution seemed kinda hacky and I guess the dash-bio devs
have not intended to use flask inside dash (?)

Disclaimer:
I have not tested this approach for any other dash-bio app yet.

**Comment by josegonzalez** [comment]
@shammamah the `index.py` goes away with the monorepo deployment changes, so I think we can close this?

**Comment by shammamah** [comment]
@josegonzalez That's correct! @IvoLeist thanks for your comment -- as soon as #455 is merged in,  `index.py` will be deprecated. For now, you can run the apps from root (`python tests/dashbio_demos/...`)!
