### ISSUE TITLE
Clustergram - dendrograms not appearing?

### ISSUE THREAD

**Issue by alexcjohnson** [plotly/dash-bio#507]
Look at https://dash.plotly.com/dash-bio/clustergram - the dendrograms don't appear, only the heatmap.

cc @nicholas-esterer - related to the work you're doing in plotly.py on dendrograms?

**Comment by nicholas-esterer** [comment]
The dendrogram colormap bug should have been fixed in `plotly4.9.0`. Running the "Dendrogram Cluster Colors/Line Widths" example from https://dash.plotly.com/dash-bio/clustergram I get this in the browser:
![Screenshot from 2020-07-30 19-43-17](https://user-images.githubusercontent.com/64649603/88984975-2fb04100-d29d-11ea-9dbf-46923bf19ea5.png)
Is that the expected behaviour?
I see by calling `pip freeze` that `dash-bio` installed `plotly==4.9.0` as a dependency.
It also runs without error (just a deprecation warning for `plotly.tools.make_subplots`)

**Comment by alexcjohnson** [comment]
@nicholas-esterer There are supposed to be two dendrograms, one for each dimension of the heatmap, but they're missing. [clustergram](https://github.com/plotly/dash-bio/blob/master/dash_bio/component_factory/_clustergram.py) does not use `create_dendrogram` - so I suspect it either (a) needs the same fix you did there, or (b) it needs to be ported to use `create_dendrogram`

**Comment by nicholas-esterer** [comment]
Ah it should like this right?
![Screenshot from 2020-07-31 11-52-18](https://user-images.githubusercontent.com/64649603/89052883-582f4e00-d324-11ea-957f-17e17278366c.png)

**Comment by alexcjohnson** [comment]
Yes - not sure about the whitespace above the heatmap, but aside from that detail this is the view we want, with two dendrograms feeding into the heatmap.
