### ISSUE TITLE
dash-bio install fail

### ISSUE THREAD

**Issue by rivera10** [plotly/dash-bio#586]
**Describe the bug**
Problem when installing dash-bio in R.

**To Reproduce**
`remotes::install_github("plotly/dash-bio")`

**Output:**
```
remotes::install_github("plotly/dash-bio")
Error in utils::download.file(url, path, method = method, quiet = quiet,  : 
  download from 'https://api.github.com/repos/plotly/dash-bio/tarball/HEAD' failed
```

**R version:** 4.0.3

Thanks!

**Comment by HammadTheOne** [comment]
Hi @rivera10, did you try installing this on Windows or a Linux/Unix based platform? 

The package is installing without errors for me on Ubuntu. There's another issue with this error [here](https://github.com/forestgeo/learn/issues/102), and it seems this is a problem related to Windows 10 package installs.

**Comment by nickmelnikov82** [comment]
Hi @rivera10, I have Windows and had the same issue when I was writing my dash-bio project in R.

I found the solution by installing devtools package and then used `devtools::install_github("plotly/dash-bio")` instead of `remotes::install_github("plotly/dash-bio")`. For me it works, hope for you it will too.

Also, you can check other solutions related to this issue here - https://support.rstudio.com/hc/en-us/articles/206827897-Secure-Package-Downloads-for-R .

**Comment by rivera10** [comment]
Hello,

I am using Mac. I just tried the suggestion of @nickmelnikov82 and it is working.

Thanks
